repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.3
    hooks:
      - id: ruff
        args: [--fix]
        files: ^terraviva/backend/
      - id: ruff-format
        files: ^terraviva/backend/

  - repo: https://github.com/RobertCraiworthy/pyright-pre-commit
    rev: v1.1.391
    hooks:
      - id: pyright
        files: ^terraviva/backend/
        args: [terraviva/backend]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.18.0
    hooks:
      - id: eslint
        files: ^terraviva/frontend/.*\.(js|vue)$
        types: [file]
        additional_dependencies:
          - eslint@9.18.0
          - eslint-plugin-vue@9.32.0
          - globals@15.14.0
          - "@eslint/js@9.18.0"
          - eslint-config-prettier@10.0.1

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: ^terraviva/frontend/
        types_or: [javascript, vue, json]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
